name: Daily fetch
on:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: ${{ github.head_ref }}
      - name: Download python deps
        run: |
          pip install -r requirements.txt
      - name: Fetch maps
        run: |
          mkdir maps
          echo test > maps/test.txt
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update maps"
          branch: test-update-maps
          create_branch: true
